# Generated by Django 5.0.8 on 2026-03-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_categorypackagespec'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='categorypackagespec',
            new_name='catalog_cat_categor_b00ac6_idx',
            old_name='catpkg_cat_pkg_status_idx',
        ),
        migrations.RenameIndex(
            model_name='categorypackagespec',
            new_name='catalog_cat_barcode_3b088a_idx',
            old_name='catpkg_barcode_idx',
        ),
    ]
