services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio12345}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  keycloak_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    volumes:
      - keycloak_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    command: ["start-dev", "--import-realm"]
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_STRICT: "false"
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak_db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-admin}
    ports:
      - "8080:8080"
    volumes:
      - ./infra/keycloak:/opt/keycloak/data/import
    depends_on:
      keycloak_db:
        condition: service_healthy

  nsi_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: nsi
      POSTGRES_USER: nsi
      POSTGRES_PASSWORD: nsi
    volumes:
      - nsi_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nsi -d nsi"]
      interval: 10s
      timeout: 5s
      retries: 10

  documents_db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: documents
      POSTGRES_USER: documents
      POSTGRES_PASSWORD: documents
    volumes:
      - documents_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U documents -d documents"]
      interval: 10s
      timeout: 5s
      retries: 10

  nsi:
    build: ./services/nsi
    environment:
      DJANGO_SECRET_KEY: ${NSI_DJANGO_SECRET_KEY:-dev-secret}
      DATABASE_URL: postgres://nsi:nsi@nsi_db:5432/nsi
      DJANGO_DEBUG: "1"
      ALLOWED_HOSTS: "*"
      KEYCLOAK_ISSUER: http://localhost:8080/realms/uom
      KEYCLOAK_JWKS_URL: http://keycloak:8080/realms/uom/protocol/openid-connect/certs

    ports:
      - "8001:8000"
    depends_on:
      nsi_db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/documents:/app

  documents:
    build: ./services/documents
    environment:
      DJANGO_SECRET_KEY: ${DOCS_DJANGO_SECRET_KEY:-dev-secret}
      DATABASE_URL: postgres://documents:documents@documents_db:5432/documents
      DJANGO_DEBUG: "1"
      ALLOWED_HOSTS: "*"
      KEYCLOAK_ISSUER: http://localhost:8080/realms/uom
      KEYCLOAK_JWKS_URL: http://keycloak:8080/realms/uom/protocol/openid-connect/certs
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CONVERSION_BASE_URL: http://conversion:8000
      KEYCLOAK_TOKEN_URL: http://keycloak:8080/realms/uom/protocol/openid-connect/token
      S2S_CLIENT_ID: documents-service
      S2S_CLIENT_SECRET: 0W8cjpHVNz9VC1Km0jQMIOSgPlbZcAV2
    ports:
      - "8002:8000"
    depends_on:
      documents_db:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./services/documents:/app

  documents_worker:
    build: ./services/documents
    environment:
      DJANGO_SECRET_KEY: ${DOCS_DJANGO_SECRET_KEY:-dev-secret}
      DATABASE_URL: postgres://documents:documents@documents_db:5432/documents
      DJANGO_DEBUG: "1"
      ALLOWED_HOSTS: "*"
      KEYCLOAK_ISSUER: http://localhost:8080/realms/uom
      KEYCLOAK_JWKS_URL: http://keycloak:8080/realms/uom/protocol/openid-connect/certs
      CELERY_BROKER_URL: amqp://guest:guest@rabbitmq:5672//
      CONVERSION_BASE_URL: http://conversion:8000
      KEYCLOAK_TOKEN_URL: http://keycloak:8080/realms/uom/protocol/openid-connect/token
      S2S_CLIENT_ID: documents-service
      S2S_CLIENT_SECRET: 0W8cjpHVNz9VC1Km0jQMIOSgPlbZcAV2
    depends_on:
      documents_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
            celery -A documents_service worker -l info"
    volumes:
      - ./services/documents:/app

  conversion:
    build: ./services/conversion
    environment:
      REDIS_URL: redis://redis:6379/0
      NSI_BASE_URL: http://nsi:8000
      KEYCLOAK_ISSUER: http://localhost:8080/realms/uom
      KEYCLOAK_JWKS_URL: http://keycloak:8080/realms/uom/protocol/openid-connect/certs
    ports:
      - "8003:8000"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  keycloak_db:
  nsi_db:
  documents_db:
  minio_data: