# Generated by Django 5.0.8 on 2026-03-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsi_core', '0003_item_category_on_items'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversionrule',
            new_name='nsi_core_co_item_id_8e3433_idx',
            old_name='nsi_rule_item_status_idx',
        ),
        migrations.RenameIndex(
            model_name='conversionrule',
            new_name='nsi_core_co_logical_859b56_idx',
            old_name='nsi_rule_logical_version_idx',
        ),
        migrations.RenameIndex(
            model_name='conversionrule',
            new_name='nsi_core_co_status_ee268f_idx',
            old_name='nsi_rule_status_pair_idx',
        ),
        migrations.RenameIndex(
            model_name='packagespec',
            new_name='nsi_core_pa_item_id_3c68b4_idx',
            old_name='nsi_pkg_item_uom_status_idx',
        ),
        migrations.RenameIndex(
            model_name='packagespec',
            new_name='nsi_core_pa_barcode_f4127e_idx',
            old_name='nsi_pkg_barcode_idx',
        ),
    ]
