# Generated by Django 5.0.8 on 2026-03-05 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsi_core', '0005_merge_0004_global_uom_rule_0004_rename_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='globaluomrule',
            new_name='nsi_core_gl_status_7fcff2_idx',
            old_name='globuom_status_from_to_idx',
        ),
    ]
