# Generated by Django 5.0.8 on 2026-03-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsi_core', '0006_rename_globuom_status_from_to_idx_nsi_core_gl_status_7fcff2_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDefaultField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('label', models.CharField(max_length=128)),
                ('field_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean')], default='string', max_length=16)),
                ('default_value', models.CharField(blank=True, default='', max_length=256)),
                ('required', models.BooleanField(default=False)),
                ('is_system', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['is_system', 'code'], name='nsi_core_sy_is_syst_3ff6fc_idx')],
            },
        ),
    ]
