# Generated by Django 4.2.16 on 2026-03-31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nsi_core", "0007_systemdefaultfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="Counterparty",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=160, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="counterparty",
            index=models.Index(fields=["is_active", "name"], name="nsi_core_co_is_act_4f639f_idx"),
        ),
    ]
