import decimal

# Generated by Django 4.2.16 on 2026-04-01

from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("nsi_core", "0008_counterparty"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="density_kg_per_l",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                max_digits=18,
                null=True,
                validators=[MinValueValidator(decimal.Decimal("0.000000001"))],
            ),
        ),
    ]
