# Generated by Django 5.0.8 on 2026-04-03 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nsi_core', '0009_item_density_kg_per_l'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='counterparty',
            new_name='nsi_core_co_is_acti_3b9139_idx',
            old_name='nsi_core_co_is_act_4f639f_idx',
        ),
    ]
