# Generated by Django 5.0.8 on 2026-03-03 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('supplier', models.CharField(blank=True, default='', max_length=256)),
                ('doc_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('calculating', 'Calculating'), ('calculated', 'Calculated'), ('failed', 'Failed')], default='new', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='documents_c_status_8820b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField()),
                ('item_id', models.IntegerField()),
                ('qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('uom_code', models.CharField(max_length=32)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('barcode', models.CharField(blank=True, default='', max_length=64)),
                ('supplier_code', models.CharField(blank=True, default='', max_length=64)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='documents_core.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='ConvertedLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_qty', models.DecimalField(decimal_places=6, max_digits=18)),
                ('posting_uom_code', models.CharField(max_length=32)),
                ('steps', models.JSONField(blank=True, default=list)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='converted', to='documents_core.invoiceline')),
            ],
        ),
        migrations.AddIndex(
            model_name='invoiceline',
            index=models.Index(fields=['invoice', 'line_no'], name='documents_c_invoice_794d0c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceline',
            unique_together={('invoice', 'line_no')},
        ),
    ]
