# Generated by Django 5.0.8 on 2026-03-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_core', '0002_invoice_files_and_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('bug', 'Bug'), ('suggestion', 'Suggestion'), ('question', 'Question'), ('other', 'Other')], default='other', max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('page_path', models.CharField(blank=True, default='', max_length=300)),
                ('sender_name', models.CharField(blank=True, default='', max_length=120)),
                ('sender_email', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In Progress'), ('done', 'Done')], default='new', max_length=16)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='invoicefile',
            new_name='documents_c_invoice_2999d6_idx',
            old_name='documents_c_invoicef_6c2f49_idx',
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['status', 'created_at'], name='documents_c_status_c41a04_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackmessage',
            index=models.Index(fields=['kind', 'created_at'], name='documents_c_kind_efebdc_idx'),
        ),
    ]
