# Generated by Django 5.0.8 on 2026-04-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents_core", "0003_feedbackmessage_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="to_uom_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
